name: Test Project

on:
  [push, pull_request]:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    containers:
      image: node:22
    steps:
      - uses: actions/checkout@v4
        with:
          node-version: 22
      - run: npm ci
      - run: npm run build


